name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  HF_USERNAME: jake-molnia
  HF_SPACE_NAME: CS553

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    environment: deployment_to_huggingface

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Setup Git configuration
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Verify Git status
      run: |
        git status
        git log -n 1

    - name: Setup Hugging Face CLI
      run: pip install huggingface_hub

    - name: Login to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: huggingface-cli login --token $HF_TOKEN

    - name: Sync to Hugging Face Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Syncing to Hugging Face Space: ${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }}"
        if ! git push https://${{ env.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }} main; then
          echo "Push failed. Attempting to resolve conflicts..."
          git config --global pull.rebase false
          git pull https://${{ env.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }} main --allow-unrelated-histories
          git push https://${{ env.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }} main
        fi

    - name: Verify sync
      run: |
        echo "Verifying sync..."
        git ls-remote --exit-code https://${{ env.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }} main

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up..."
        huggingface-cli logout
        git config --global --unset user.name
        git config --global --unset user.email

    - name: Notify Discord on failure
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        curl -H "Content-Type: application/json" -d '{
          "username": "GitHub Actions",
          "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
          "content": "Sync to Hugging Face Hub failed for ${{ github.repository }}. [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
        }' $DISCORD_WEBHOOK
